### ISSUE TITLE
Thanks in advance Chuck

### ISSUE THREAD

**Issue by Enemall** [Chuckleberry-Finn/errorMagnifier#2]
Hi Chuck,

Please look at this if you find the time. I can't figure out what mods the error is related to. Console.txt uploaded and here's the copy of the error as it appears through Magnifier. 

`se.krka.kahlua.vm.KahluaException: HGWH_ProceduralDistributions.lua:16: ')' expected near `;`
    at org.luaj.kahluafork.compiler.LexState.lexerror(LexState.java:278)
    at org.luaj.kahluafork.compiler.LexState.syntaxerror(LexState.java:289)
    at org.luaj.kahluafork.compiler.LexState.error_expected(LexState.java:683)
    at org.luaj.kahluafork.compiler.LexState.check_match(LexState.java:713)
    at org.luaj.kahluafork.compiler.LexState.funcargs(LexState.java:1062)
    at org.luaj.kahluafork.compiler.LexState.primaryexp(LexState.java:1156)
    at org.luaj.kahluafork.compiler.LexState.exprstat(LexState.java:1691)
    at org.luaj.kahluafork.compiler.LexState.statement(LexState.java:1779)
    at org.luaj.kahluafork.compiler.LexState.chunk(LexState.java:1790)
    at org.luaj.kahluafork.compiler.LexState.compile(LexState.java:198)
    at se.krka.kahlua.luaj.compiler.LuaCompiler.loadis(LuaCompiler.java:132)
    at se.krka.kahlua.luaj.compiler.LuaCompiler.loadis(LuaCompiler.java:124)
    at zombie.Lua.LuaManager.RunLuaInternal(LuaManager.java:546)
    at zombie.Lua.LuaManager.RunLua(LuaManager.java:510)
    at zombie.Lua.LuaManager.RunLua(LuaManager.java:496)
    at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:342)
    at zombie.Lua.LuaManager.LoadDirBase(LuaManager.java:264)
    at zombie.gameStates.GameLoadingState.enter(GameLoadingState.java:97)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:145)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

Thanks,
And thanks for all your effort everywhere.

[console.txt](https://github.com/user-attachments/files/15612309/console.txt)

**Comment by Chuckleberry-Finn** [comment]
` HGWH_ProceduralDistributions.lua`

🤷 What ever mod this could be.
